"""Tests for CLI cache estimation helpers and new flags."""

import json
import tempfile
from pathlib import Path

from typer.testing import CliRunner

from wiki import cli
from wiki.cli import is_note_stale
from wiki.generate.notes import compute_chunks_hash
from wiki.llm.prompts import PROMPT_VERSION
from wiki.schemas import ResourceRecord, ResourceStatus, SourceType, WebpageChunk
from wiki.registry import registry


def _record_with_chunks(tmp_path: Path) -> tuple[ResourceRecord, list[WebpageChunk]]:
    norm_dir = tmp_path / "normalized"
    norm_dir.mkdir()
    note_path = tmp_path / "note.md"
    note_path.write_text("# Note\n", encoding="utf-8")
    chunks = [
        WebpageChunk(
            resource_id="webpage:test",
            chunk_id="chunk-001",
            source_type=SourceType.WEBPAGE,
            text="RAG retrieves context.",
            citation_label="paragraph 1",
            url="https://example.com",
        )
    ]
    with open(norm_dir / "chunks.jsonl", "w", encoding="utf-8") as f:
        for chunk in chunks:
            f.write(json.dumps(chunk.model_dump(), default=str) + "\n")

    record = ResourceRecord(
        id="webpage:test",
        source_type=SourceType.WEBPAGE,
        canonical_id="webpage:test",
        original_url="https://example.com",
        local_normalized_path=norm_dir,
        generated_note_path=note_path,
        source_chunks_hash=compute_chunks_hash(chunks),
        prompt_version=PROMPT_VERSION,
        llm_model="mock-model",
    )
    return record, chunks


def test_would_regenerate_note_detects_cache_hit(tmp_path, monkeypatch):
    record, _ = _record_with_chunks(tmp_path)
    monkeypatch.setattr(cli.config, "LLM_PROVIDER", "mock")

    assert cli.would_regenerate_note(record) is False


def test_would_regenerate_note_respects_force(tmp_path, monkeypatch):
    record, _ = _record_with_chunks(tmp_path)
    monkeypatch.setattr(cli.config, "LLM_PROVIDER", "mock")

    assert cli.would_regenerate_note(record, force=True) is True


def test_would_regenerate_note_detects_prompt_version_change(tmp_path, monkeypatch):
    record, _ = _record_with_chunks(tmp_path)
    record.prompt_version = "old"
    monkeypatch.setattr(cli.config, "LLM_PROVIDER", "mock")

    assert cli.would_regenerate_note(record) is True


def test_only_stale_filters_by_prompt_version():
    """--only-stale filters based on provider+model staleness, not just prompt version."""
    all_records = list(registry.get_all())

    # With --provider mock, records generated by mock with mock-model at v4
    # should NOT be stale (provider and model match).
    # But records with failed_retryable status are always stale.
    stale_for_mock = [r for r in all_records if is_note_stale(r, "mock", "mock-model")]
    current_for_mock = [r for r in all_records if not is_note_stale(r, "mock", "mock-model")]
    # 16 processed + 1 failed_retryable = 17 total
    # failed_retryable is always stale regardless of provider
    assert len(stale_for_mock) == 1, f"Expected 1 stale for mock (failed_retryable), got {len(stale_for_mock)}"
    assert len(current_for_mock) == 16, f"Expected 16 current for mock, got {len(current_for_mock)}"

    # With --provider ollama_cloud, ALL mock-generated records should be stale
    # (because mock != ollama_cloud)
    stale_for_ollama = [r for r in all_records if is_note_stale(r, "ollama_cloud", "glm-5.1:cloud")]
    assert len(stale_for_ollama) == len(all_records), (
        f"Expected all {len(all_records)} records stale for ollama_cloud, got {len(stale_for_ollama)}"
    )


def test_get_provider_by_name_mock():
    """get_provider_by_name('mock') returns MockProvider."""
    provider = cli.get_provider_by_name("mock")
    assert isinstance(provider, cli.MockProvider)


def test_get_provider_by_name_unknown_raises():
    """get_provider_by_name with unknown provider raises typer.Exit."""
    import pytest
    with pytest.raises((SystemExit, Exception)):
        cli.get_provider_by_name("nonexistent_provider")


def test_list_stale_notes_command():
    """list-stale-notes command should run without error."""
    result = CliRunner().invoke(cli.app, ["list-stale-notes"])
    assert result.exit_code == 0
    assert "Stale Notes" in result.output or "current prompt version" in result.output


def test_process_new_dry_run_with_skip_ingest(monkeypatch, tmp_path):
    """--skip-ingest --dry-run should show skip message for resources with chunks."""
    records = list(registry.get_all())
    if not records:
        return
    record = records[0]
    if not record.local_normalized_path:
        return
    chunks_path = Path(record.local_normalized_path) / "chunks.jsonl"
    if not chunks_path.exists():
        return

    result = CliRunner().invoke(cli.app, [
        "process-new", "--dry-run", "--force", "--skip-ingest", "--limit", "1"
    ])
    assert result.exit_code == 0
    assert "would call LLM" in result.output.lower() or "cache hit" in result.output.lower() or "skip" in result.output.lower()


def test_process_new_provider_override_dry_run():
    """--provider mock --dry-run should override the LLM provider."""
    result = CliRunner().invoke(cli.app, [
        "process-new", "--dry-run", "--force", "--provider", "mock", "--limit", "1"
    ])
    assert result.exit_code == 0


class TestIsNoteStale:
    """Unit tests for is_note_stale covering each staleness condition."""

    def _make_record(self, **overrides):
        """Create a minimal ResourceRecord for testing."""
        note_path = Path(tempfile.mktemp(suffix=".md"))
        defaults = dict(
            id="test:abc123",
            source_type=SourceType.WEBPAGE,
            canonical_id="test:abc123",
            original_url="https://example.com",
            title="Test Resource",
            status=ResourceStatus.PROCESSED,
            prompt_version=PROMPT_VERSION,
            llm_provider="mock",
            llm_model="mock-model",
            generated_note_path=note_path,
            source_chunks_hash="abc123",
            local_normalized_path=None,
        )
        defaults.update(overrides)
        record = ResourceRecord(**defaults)
        # Create the note file so .exists() passes
        note_path.parent.mkdir(parents=True, exist_ok=True)
        note_path.touch()
        return record

    def test_current_for_matching_provider_model(self):
        """Note at current version, matching provider and model, is not stale."""
        record = self._make_record(
            llm_provider="ollama_cloud",
            llm_model="glm-5.1:cloud",
        )
        assert not is_note_stale(record, "ollama_cloud", "glm-5.1:cloud")

    def test_stale_for_wrong_provider(self):
        """Mock-generated note is stale for ollama_cloud."""
        record = self._make_record()
        assert is_note_stale(record, "ollama_cloud", "glm-5.1:cloud")

    def test_stale_for_wrong_model(self):
        """Note with wrong model is stale for matching provider."""
        note_path = Path(tempfile.mktemp(suffix=".md"))
        note_path.parent.mkdir(parents=True, exist_ok=True)
        note_path.touch()
        record = self._make_record(
            llm_provider="ollama_cloud",
            llm_model="old-model",
            generated_note_path=note_path,
        )
        assert is_note_stale(record, "ollama_cloud", "glm-5.1:cloud")

    def test_stale_for_old_prompt_version(self):
        """Note with old prompt version is stale regardless of provider."""
        note_path = Path(tempfile.mktemp(suffix=".md"))
        note_path.parent.mkdir(parents=True, exist_ok=True)
        note_path.touch()
        record = self._make_record(
            prompt_version="harish_llm_wiki_v3",
            llm_provider="ollama_cloud",
            llm_model="glm-5.1:cloud",
            generated_note_path=note_path,
        )
        assert is_note_stale(record, "ollama_cloud", "glm-5.1:cloud")

    def test_stale_failed_retryable(self):
        """failed_retryable status always means stale, even with matching provider."""
        note_path = Path(tempfile.mktemp(suffix=".md"))
        note_path.parent.mkdir(parents=True, exist_ok=True)
        note_path.touch()
        record = self._make_record(
            status=ResourceStatus.FAILED_RETRYABLE,
            llm_provider="ollama_cloud",
            llm_model="glm-5.1:cloud",
            generated_note_path=note_path,
        )
        assert is_note_stale(record, "ollama_cloud", "glm-5.1:cloud")

    def test_stale_missing_note_path(self):
        """Note with non-existent generated_note_path is stale."""
        record = self._make_record(
            generated_note_path=Path("/nonexistent/path.md"),
        )
        assert is_note_stale(record, "mock", "mock-model")

    def test_mock_current_for_mock(self):
        """Mock-generated note is current for mock provider with mock-model."""
        record = self._make_record()
        assert not is_note_stale(record, "mock", "mock-model")
