"""Presentation branding configuration for the generated site."""

from __future__ import annotations

import json
import os
from pathlib import Path
from typing import Any

import yaml
from pydantic import BaseModel, Field


class HeroBranding(BaseModel):
    """Homepage hero text."""

    name: str = "Harish LLM Wiki"
    text: str = "Personal Learning Wiki"
    tagline: str = "A static wiki generated from YouTube, blogs, and LLM-generated notes"


class GitHubBranding(BaseModel):
    """Public repository links used by the static site."""

    owner: str = "pillaiharish"
    repo: str = "harish-llm-wiki"
    branch: str = "main"

    @property
    def edit_pattern(self) -> str:
        return (
            f"https://github.com/{self.owner}/{self.repo}/edit/"
            f"{self.branch}/site/docs/:path"
        )

    @property
    def blob_base(self) -> str:
        return f"https://github.com/{self.owner}/{self.repo}/blob/{self.branch}"


class SiteBranding(BaseModel):
    """Site-level visible branding."""

    title: str = "Harish LLM Wiki"
    owner_name: str = "Harish"
    description: str = "Personal static learning wiki"
    footer_message: str = "Generated with Harish LLM Wiki"
    copyright: str = "Copyright © 2024-2026"
    hero: HeroBranding = Field(default_factory=HeroBranding)
    github: GitHubBranding = Field(default_factory=GitHubBranding)


class RuntimeIdentityBranding(BaseModel):
    """Public runtime display identity defaults.

    This is intentionally presentation-only. Provider names, API keys,
    local paths, and processing configuration do not belong here.
    """

    default_owner_name: str = "Harish"
    default_site_title: str = "Harish LLM Wiki"
    allow_browser_override: bool = True


class WikiBrandingConfig(BaseModel):
    """Root branding config object."""

    site: SiteBranding = Field(default_factory=SiteBranding)
    runtime_identity: RuntimeIdentityBranding = Field(
        default_factory=RuntimeIdentityBranding
    )


def repo_root() -> Path:
    """Return the project repository root."""

    return Path(__file__).resolve().parents[2]


def default_config_path() -> Path:
    """Return the default branding config path."""

    return repo_root() / "wiki_config.yaml"


def _deep_merge(base: dict[str, Any], override: dict[str, Any]) -> dict[str, Any]:
    merged = dict(base)
    for key, value in override.items():
        if isinstance(value, dict) and isinstance(merged.get(key), dict):
            merged[key] = _deep_merge(merged[key], value)
        else:
            merged[key] = value
    return merged


def load_branding_config(path: str | Path | None = None) -> WikiBrandingConfig:
    """Load branding config from YAML, falling back to defaults.

    The optional ``LLM_WIKI_CONFIG`` environment variable can point to
    an alternate YAML file. This config intentionally covers public
    presentation text only; provider secrets stay in ``.env`` and
    environment variables.
    """

    default = WikiBrandingConfig()
    selected = path or os.getenv("LLM_WIKI_CONFIG") or default_config_path()
    selected_path = Path(selected).expanduser()
    if not selected_path.is_absolute():
        selected_path = Path.cwd() / selected_path
    if not selected_path.exists():
        return default

    loaded = yaml.safe_load(selected_path.read_text(encoding="utf-8")) or {}
    if not isinstance(loaded, dict):
        return default

    merged = _deep_merge(default.model_dump(), loaded)
    return WikiBrandingConfig.model_validate(merged)


def vitepress_branding_payload(config: WikiBrandingConfig | None = None) -> dict[str, str]:
    """Return the VitePress-facing branding payload."""

    cfg = config or load_branding_config()
    site = cfg.site
    return {
        "title": site.title,
        "description": site.description,
        "footerMessage": site.footer_message,
        "copyright": site.copyright,
        "githubEditPattern": site.github.edit_pattern,
        "githubBlobBase": site.github.blob_base,
        "ogTitle": site.title,
        "ogDescription": site.description,
    }


def runtime_identity_payload(config: WikiBrandingConfig | None = None) -> dict[str, Any]:
    """Return the public browser-facing runtime identity payload."""

    cfg = config or load_branding_config()
    identity = cfg.runtime_identity
    return {
        "schemaVersion": "runtime_identity_v1",
        "defaultOwnerName": identity.default_owner_name,
        "defaultSiteTitle": identity.default_site_title,
        "allowBrowserOverride": identity.allow_browser_override,
    }


def render_vitepress_branding(config: WikiBrandingConfig | None = None) -> str:
    """Render the generated VitePress branding module."""

    payload = vitepress_branding_payload(config)
    body = json.dumps(payload, indent=2, ensure_ascii=False)
    return (
        "// Generated by wiki build-site --refresh from wiki_config.yaml.\n"
        "// Do not put secrets in this file.\n"
        f"export const siteBranding = {body} as const\n"
    )


def render_public_runtime_identity(config: WikiBrandingConfig | None = None) -> str:
    """Render the public runtime identity JSON artifact."""

    return json.dumps(runtime_identity_payload(config), indent=2, ensure_ascii=False) + "\n"


def write_vitepress_branding(
    output_path: Path | None = None,
    config: WikiBrandingConfig | None = None,
) -> Path:
    """Write the generated VitePress branding module."""

    out = output_path or repo_root() / "site" / "docs" / ".vitepress" / "site-branding.generated.ts"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(render_vitepress_branding(config), encoding="utf-8")
    return out


def write_public_runtime_identity(
    output_path: Path | None = None,
    config: WikiBrandingConfig | None = None,
) -> Path:
    """Write the public runtime identity JSON artifact."""

    out = output_path or repo_root() / "site" / "docs" / "public" / "site-branding.json"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(render_public_runtime_identity(config), encoding="utf-8")
    return out


def write_branding_config(
    config: WikiBrandingConfig,
    path: str | Path | None = None,
) -> Path:
    """Write the public presentation config to YAML."""

    selected = path or os.getenv("LLM_WIKI_CONFIG") or default_config_path()
    out = Path(selected).expanduser()
    if not out.is_absolute():
        out = Path.cwd() / out
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(
        yaml.safe_dump(config.model_dump(), sort_keys=False, allow_unicode=True),
        encoding="utf-8",
    )
    return out


def configure_runtime_identity(
    *,
    owner_name: str,
    title: str,
    config_path: str | Path | None = None,
    vitepress_output_path: Path | None = None,
    public_identity_output_path: Path | None = None,
) -> tuple[Path, Path, Path]:
    """Update launch-time display identity and regenerate branding artifacts."""

    owner = owner_name.strip()
    site_title = title.strip()
    if not owner:
        raise ValueError("owner_name cannot be empty")
    if not site_title:
        raise ValueError("title cannot be empty")

    selected_config = config_path or os.getenv("LLM_WIKI_CONFIG") or default_config_path()
    cfg = load_branding_config(selected_config)
    cfg.site.owner_name = owner
    cfg.site.title = site_title
    cfg.site.hero.name = site_title
    cfg.site.footer_message = f"Generated with {site_title}"
    cfg.runtime_identity.default_owner_name = owner
    cfg.runtime_identity.default_site_title = site_title

    config_out = write_branding_config(cfg, selected_config)
    vitepress_out = write_vitepress_branding(vitepress_output_path, config=cfg)
    public_out = write_public_runtime_identity(public_identity_output_path, config=cfg)
    return config_out, vitepress_out, public_out
