"""Presentation branding configuration for the generated site."""

from __future__ import annotations

import json
import os
from pathlib import Path
from typing import Any

import yaml
from pydantic import BaseModel, Field


class HeroBranding(BaseModel):
    """Homepage hero text."""

    name: str = "Harish LLM Wiki"
    text: str = "Personal Learning Wiki"
    tagline: str = "A static wiki generated from YouTube, blogs, and LLM-generated notes"


class GitHubBranding(BaseModel):
    """Public repository links used by the static site."""

    owner: str = "pillaiharish"
    repo: str = "harish-llm-wiki"
    branch: str = "main"

    @property
    def edit_pattern(self) -> str:
        return (
            f"https://github.com/{self.owner}/{self.repo}/edit/"
            f"{self.branch}/site/docs/:path"
        )

    @property
    def blob_base(self) -> str:
        return f"https://github.com/{self.owner}/{self.repo}/blob/{self.branch}"


class SiteBranding(BaseModel):
    """Site-level visible branding."""

    title: str = "Harish LLM Wiki"
    owner_name: str = "Harish"
    description: str = "Personal static learning wiki"
    footer_message: str = "Generated with Harish LLM Wiki"
    copyright: str = "Copyright © 2024-2026"
    hero: HeroBranding = Field(default_factory=HeroBranding)
    github: GitHubBranding = Field(default_factory=GitHubBranding)


class WikiBrandingConfig(BaseModel):
    """Root branding config object."""

    site: SiteBranding = Field(default_factory=SiteBranding)


def repo_root() -> Path:
    """Return the project repository root."""

    return Path(__file__).resolve().parents[2]


def default_config_path() -> Path:
    """Return the default branding config path."""

    return repo_root() / "wiki_config.yaml"


def _deep_merge(base: dict[str, Any], override: dict[str, Any]) -> dict[str, Any]:
    merged = dict(base)
    for key, value in override.items():
        if isinstance(value, dict) and isinstance(merged.get(key), dict):
            merged[key] = _deep_merge(merged[key], value)
        else:
            merged[key] = value
    return merged


def load_branding_config(path: str | Path | None = None) -> WikiBrandingConfig:
    """Load branding config from YAML, falling back to defaults.

    The optional ``LLM_WIKI_CONFIG`` environment variable can point to
    an alternate YAML file. This config intentionally covers public
    presentation text only; provider secrets stay in ``.env`` and
    environment variables.
    """

    default = WikiBrandingConfig()
    selected = path or os.getenv("LLM_WIKI_CONFIG") or default_config_path()
    selected_path = Path(selected).expanduser()
    if not selected_path.is_absolute():
        selected_path = Path.cwd() / selected_path
    if not selected_path.exists():
        return default

    loaded = yaml.safe_load(selected_path.read_text(encoding="utf-8")) or {}
    if not isinstance(loaded, dict):
        return default

    merged = _deep_merge(default.model_dump(), loaded)
    return WikiBrandingConfig.model_validate(merged)


def vitepress_branding_payload(config: WikiBrandingConfig | None = None) -> dict[str, str]:
    """Return the VitePress-facing branding payload."""

    cfg = config or load_branding_config()
    site = cfg.site
    return {
        "title": site.title,
        "description": site.description,
        "footerMessage": site.footer_message,
        "copyright": site.copyright,
        "githubEditPattern": site.github.edit_pattern,
        "githubBlobBase": site.github.blob_base,
        "ogTitle": site.title,
        "ogDescription": site.description,
    }


def render_vitepress_branding(config: WikiBrandingConfig | None = None) -> str:
    """Render the generated VitePress branding module."""

    payload = vitepress_branding_payload(config)
    body = json.dumps(payload, indent=2, ensure_ascii=False)
    return (
        "// Generated by wiki build-site --refresh from wiki_config.yaml.\n"
        "// Do not put secrets in this file.\n"
        f"export const siteBranding = {body} as const\n"
    )


def write_vitepress_branding(
    output_path: Path | None = None,
    config: WikiBrandingConfig | None = None,
) -> Path:
    """Write the generated VitePress branding module."""

    out = output_path or repo_root() / "site" / "docs" / ".vitepress" / "site-branding.generated.ts"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(render_vitepress_branding(config), encoding="utf-8")
    return out
