// Generated by wiki build-site --refresh from wiki_config.yaml.
// Do not put secrets in this file.
export const siteBranding = {
  "title": "Harish LLM Wiki",
  "description": "Personal static learning wiki",
  "footerMessage": "Generated with Harish LLM Wiki",
  "copyright": "Copyright © 2024-2026",
  "githubEditPattern": "https://github.com/pillaiharish/harish-llm-wiki/edit/main/site/docs/:path",
  "githubBlobBase": "https://github.com/pillaiharish/harish-llm-wiki/blob/main",
  "ogTitle": "Harish LLM Wiki",
  "ogDescription": "Personal static learning wiki"
} as const
