"""Public schema for the mock-answer generator (Prompt 34 MVP closure).

This module defines the on-the-wire shape of a deterministic
no-LLM mock answer. The answer is intentionally simple: it
contains a stable banner, a short extractive summary, the
list of citation labels used in the body, the source ids
those citations point to, and a small bag of debug fields
(mode, query, total_chunks, used_chars, schema_version,
mock_tag, is_mock).

The dataclass is frozen so the answer is immutable and the
``to_dict()`` projection is the contract for the JSON CLI
output and the static report page. The schema is
intentionally small: it carries the minimum metadata a
downstream evaluator (:mod:`wiki.rag_eval`) needs to validate
the answer.

The schema has one dataclass:

- :class:`MockAnswer` — the answer envelope. It carries the
  body text, the citation labels used in the body, the
  source ids those citations point to, the schema metadata,
  the totals, and the mock/no-LLM tags.

The module has no project imports. The dataclass is a plain
frozen Python type that can be unit-tested without any of
the retrieval, context-pack, or model-provider modules.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any


# =============================================================================
# Constants
# =============================================================================


#: Schema version string for the mock answer. Bumped only
#: when the public JSON shape changes in a breaking way.
#: The CLI emits this string as the ``schema_version`` field
#: of the JSON output and the first line of the readable
#: report.
MOCK_ANSWER_SCHEMA_VERSION: str = "mock_answer_v1"

#: Implementation version string. Distinct from the schema
#: version: the schema version tracks the public JSON shape;
#: the implementation version tracks the body-generation
#: algorithm. Bumped when the extractive summarizer changes
#: in a way that produces a different body for the same
#: input.
MOCK_ANSWER_VERSION: str = "mock_answer_v1_impl1"

#: Stable banner that the readable formatter and the body
#: itself prepend. The downstream evaluator greps for this
#: string to confirm the answer is mock/no-LLM.
MOCK_ANSWER_BANNER: str = "MOCK / NO-LLM ANSWER"

#: Stable tag the downstream evaluator greps for to confirm
#: the answer is mock/no-LLM. The tag is also exposed in the
#: JSON output.
MOCK_ANSWER_TAG: str = "no-llm-mock"

#: Stable string the body uses when the context is empty.
#: The string is intentionally explicit so the evaluator can
#: assert the body is non-empty-but-clearly-empty (i.e. the
#: generator is not silent).
NO_CONTEXT_BODY: str = (
    "I don't know based on the provided context. "
    "(MOCK / NO-LLM ANSWER — no context chunks were retrieved.)"
)

#: Maximum number of sentences the extractive summarizer
#: extracts from a single chunk. The MVP closure is
#: intentionally small: the body must be small enough to
#: read at a glance, and the evaluator must be able to
#: grep for citation labels and count them.
MAX_SENTENCES_PER_CHUNK: int = 3

#: Maximum total body length in characters. The MVP closure
#: caps the body so a long context pack cannot produce a
#: runaway body. The cap is applied to the body *after* the
#: citations are appended, so the citation labels always
#: survive the trim.
MAX_BODY_CHARS: int = 4000


# =============================================================================
# Mock answer
# =============================================================================


@dataclass(frozen=True)
class MockAnswer:
    """The deterministic mock answer envelope.

    Fields
    ------
    schema_version:
        The :data:`MOCK_ANSWER_SCHEMA_VERSION` string. Always
        the first field of the JSON projection.
    answer_version:
        The :data:`MOCK_ANSWER_VERSION` string.
    query:
        The user query. Stored verbatim.
    mode:
        The retrieval mode used to build the context pack.
    body:
        The answer body. Always starts with the MOCK /
        NO-LLM banner. When the context is empty, the body
        is :data:`NO_CONTEXT_BODY` (which itself starts with
        the MOCK / NO-LLM banner).
    citation_labels:
        The list of citation labels the body used. Always a
        subset of the labels in the context pack.
    source_ids:
        The list of resource ids those citations point to.
    total_chunks:
        The number of chunks in the context pack.
    used_chars:
        The total number of characters consumed by the
        ``chunks[].text`` fields of the context pack.
    mock_tag:
        A small stable string (:data:`MOCK_ANSWER_TAG`) the
        downstream evaluator can use to detect that the
        answer was generated by the no-LLM MVP closure.
    is_mock:
        ``True``. The field exists for symmetry with future
        non-mock providers and to make the no-LLM intent
        explicit in the JSON output.
    used_chunk_ids:
        The list of chunk ids the body quoted. The list is
        deduplicated and stable.
    used_chunk_ranks:
        The 1-based ranks (in the context pack) of the
        chunks the body quoted. The list is in the same
        order as :attr:`used_chunk_ids` and is the canonical
        way for the evaluator to know which chunks were used.
    """

    schema_version: str
    answer_version: str
    query: str
    mode: str
    body: str
    citation_labels: list = field(default_factory=list)
    source_ids: list = field(default_factory=list)
    total_chunks: int = 0
    used_chars: int = 0
    mock_tag: str = MOCK_ANSWER_TAG
    is_mock: bool = True
    used_chunk_ids: list = field(default_factory=list)
    used_chunk_ranks: list = field(default_factory=list)

    def to_dict(self) -> dict[str, Any]:
        """Project to a dict in stable field order.

        The top-level key order is fixed: ``schema_version``
        is the first key, followed by the template metadata,
        the body, the citation list, the totals, and the
        mock/no-LLM tags.
        """
        return {
            "schema_version": self.schema_version,
            "answer_version": self.answer_version,
            "query": self.query,
            "mode": self.mode,
            "body": self.body,
            "citation_labels": list(self.citation_labels),
            "source_ids": list(self.source_ids),
            "total_chunks": int(self.total_chunks),
            "used_chars": int(self.used_chars),
            "mock_tag": self.mock_tag,
            "is_mock": bool(self.is_mock),
            "used_chunk_ids": list(self.used_chunk_ids),
            "used_chunk_ranks": list(self.used_chunk_ranks),
        }


__all__ = [
    "MAX_BODY_CHARS",
    "MAX_SENTENCES_PER_CHUNK",
    "MOCK_ANSWER_BANNER",
    "MOCK_ANSWER_SCHEMA_VERSION",
    "MOCK_ANSWER_TAG",
    "MOCK_ANSWER_VERSION",
    "MockAnswer",
    "NO_CONTEXT_BODY",
]
